
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // 應用程式執行期走連線池(pooler, 6543)
    url: env("DATABASE_URL"),
    // migration / introspection 走直連(5432);連線池不支援 DDL 與 advisory lock,
    // 少了這條會讓 prisma migrate 誤用 6543 而卡死。
    directUrl: env("DIRECT_URL"),
  },
});
